version: '3.1'

services:
  goacs-db:
    image: mariadb:10.4
    container_name: goacs-db
    restart: always
    volumes:
      - ./contrib/database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306

  mongodb:
    image: mongo:latest


networks:
  default: