version: '3.1'

services:
  goacs-db:
    image: mariadb:10.4
    container_name: goacs-db
    restart: always
    volumes:
      - goacs-database-file:/var/lib/mysql
      - ./contrib/database:/docker-entrypoint-initdb.d
      - ./contrib/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  default:

volumes:
  goacs-database-file:
    driver: local